# Generated by Django 4.2.23 on 2025-06-24 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Masa Adı')),
                ('playstation_ip', models.GenericIPAddressField(verbose_name='PlayStation IP Adresi')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=50.0, max_digits=6, verbose_name='Saatlik Ücret')),
                ('status', models.CharField(choices=[('available', 'Müsait'), ('occupied', 'Dolu'), ('maintenance', 'Bakımda')], default='available', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Masa',
                'verbose_name_plural': 'Masalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Başlama Zamanı')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Toplam Tutar')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tables.table', verbose_name='Masa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Çalışan')),
            ],
            options={
                'verbose_name': 'Seans',
                'verbose_name_plural': 'Seanslar',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PlayStationDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('PS4', 'PlayStation 4'), ('PS5', 'PlayStation 5')], max_length=10, verbose_name='Cihaz Tipi')),
                ('mac_address', models.CharField(max_length=17, verbose_name='MAC Adresi')),
                ('is_online', models.BooleanField(default=False, verbose_name='Online')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Son Görülme')),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playstation', to='tables.table', verbose_name='Masa')),
            ],
            options={
                'verbose_name': 'PlayStation',
                'verbose_name_plural': 'PlayStation Cihazları',
            },
        ),
    ]
