# Generated by Django 4.2.23 on 2025-06-25 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ürün Adı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Fiyat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tables.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='gaming_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Oyun Tutarı'),
        ),
        migrations.AddField(
            model_name='session',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6, verbose_name='Saatlik Ücret'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Ödendi'),
        ),
        migrations.AddField(
            model_name='session',
            name='is_reset',
            field=models.BooleanField(default=False, verbose_name='Reset Edildi'),
        ),
        migrations.AddField(
            model_name='session',
            name='opening_fee',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6, verbose_name='Masa Açma Ücreti'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='products_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ürün Tutarı'),
        ),
        migrations.AddField(
            model_name='table',
            name='opening_fee',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6, verbose_name='Masa Açma Ücreti'),
        ),
        migrations.CreateModel(
            name='SessionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Birim Fiyat')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Toplam Fiyat')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Zamanı')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.product', verbose_name='Ürün')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tables.session', verbose_name='Seans')),
            ],
            options={
                'verbose_name': 'Seans Ürünü',
                'verbose_name_plural': 'Seans Ürünleri',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=20, unique=True, verbose_name='Fiş Numarası')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Kesilme Zamanı')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kesen Çalışan')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='tables.session', verbose_name='Seans')),
            ],
            options={
                'verbose_name': 'Fiş',
                'verbose_name_plural': 'Fişler',
                'ordering': ['-issued_at'],
            },
        ),
    ]
