# Generated by Django 4.2.23 on 2025-06-26 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0002_category_product_session_gaming_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Mevcut Stok'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_stock_level',
            field=models.PositiveIntegerField(default=100, verbose_name='Maksimum Stok Seviyesi'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock_level',
            field=models.PositiveIntegerField(default=5, verbose_name='Minimum Stok Seviyesi'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_unit',
            field=models.CharField(default='adet', max_length=20, verbose_name='Stok Birimi'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Stok Girişi'), ('out', 'Stok Çıkışı'), ('sale', 'Satış'), ('waste', 'Fire/İmha'), ('adjustment', 'Düzeltme')], max_length=20, verbose_name='Hareket Tipi')),
                ('quantity', models.IntegerField(verbose_name='Miktar')),
                ('old_stock', models.PositiveIntegerField(verbose_name='Önceki Stok')),
                ('new_stock', models.PositiveIntegerField(verbose_name='Yeni Stok')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Birim Maliyet')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Toplam Maliyet')),
                ('supplier', models.CharField(blank=True, max_length=100, verbose_name='Tedarikçi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Zamanı')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='tables.product', verbose_name='Ürün')),
                ('session_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movement', to='tables.sessionproduct', verbose_name='Seans Ürünü')),
            ],
            options={
                'verbose_name': 'Stok Hareketi',
                'verbose_name_plural': 'Stok Hareketleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
