# Generated by Django 4.2.23 on 2025-06-28 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_product_current_stock_product_max_stock_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True, verbose_name='Rapor Tarihi')),
                ('total_receipts', models.IntegerField(default=0, verbose_name='Toplam Fiş')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Gelir')),
                ('gaming_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Oyun Geliri')),
                ('products_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ürün Geliri')),
                ('total_sessions', models.IntegerField(default=0, verbose_name='Toplam Seans')),
                ('avg_session_duration', models.IntegerField(default=0, verbose_name='Ortalama Seans Süresi (dk)')),
                ('email_sent', models.BooleanField(default=False, verbose_name='E-posta Gönderildi')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='E-posta Gönderilme Zamanı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Günlük Rapor',
                'verbose_name_plural': 'Günlük Raporlar',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('daily_report', 'Günlük Rapor'), ('receipt_copy', 'Fiş Kopyası'), ('low_stock_alert', 'Düşük Stok Uyarısı')], max_length=20)),
                ('recipients', models.TextField()),
                ('subject', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('sent', 'Gönderildi'), ('failed', 'Başarısız')], max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'E-posta Log',
                'verbose_name_plural': 'E-posta Logları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ayar Adı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'E-posta Ayarı',
                'verbose_name_plural': 'E-posta Ayarları',
            },
        ),
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta Adresi')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('recipient_type', models.CharField(choices=[('daily_report', 'Günlük Rapor'), ('receipt_copy', 'Fiş Kopyası'), ('low_stock_alert', 'Düşük Stok Uyarısı')], max_length=20, verbose_name='Rapor Türü')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='tables.emailsetting')),
            ],
            options={
                'verbose_name': 'E-posta Alıcısı',
                'verbose_name_plural': 'E-posta Alıcıları',
            },
        ),
    ]
